### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by Sergunia** [Sergunia/prog_Bakumenko#10]
cd68eea5a8fe6448fc65a8f6c1da8c63b2af1e06
@antosha417
minimalism_1.py

**Comment by Sergunia** [comment]
eb2e9544e496cb89cc35800f04ad8c420e3225a3
@antosha417
minimalism_1.py

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.
Пока ставлю тебе 0,8  за задачу, чтобы поднять поправь код.

**Comment by Sergunia** [comment]
commit 911525f035c7e3c693a6d90d2eac82b952c06fa9
@antosha417
