### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by Sergunia** [Sergunia/prog_Bakumenko#11]
eb2e9544e496cb89cc35800f04ad8c420e3225a3
@antosha417
animation_minimalism.py

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

Нет документации

Добавь документацию. 

Нарисуй посетителя используя циклы, будет меньше кода и его будет приятнее читать. 

Двигай посетителя тоже циклом. Предлагаю сделать массив куда ты положишь его части, а потом пройдёшься циклом про этому массиву

**Comment by antosha417** [comment]
Пока ставлю тебе  0,6 за задачу, чтобы поднять поправь код.

**Comment by Sergunia** [comment]
commit 0bb398a1a860c7efe5967f5cb58f7e80bbee15c4
@antosha417 
Я сделал цикл для move() и для window().  Дописал документацию для некоторых функций. Как красиво в документации указать используемые функции и переменные?

**Comment by antosha417** [comment]
Вот есть цикл:
```python 
for k in range (len(Elements)):
            Elements[k].draw(window)
```
Обычно такой цикл пишут когда нужно изменять елементы Elements. Ты можешь написать `Elements[k] = someting`.
А в твоём случае компактней и понятней можно написать так:
```python 
for elem in Elements:
            elem.draw(window)
```

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.
Пока ставлю тебе 0,9  за задачу, чтобы поднять поправь код.

**Comment by Sergunia** [comment]
commit 25f0ab91fc06e688e055550b9026d806e51b2315
@antosha417 
Я перепутал -написал в коммите: ничего не менял, но на самом деле я добавил документацию и поправил пеп
