### ISSUE TITLE
Сразу 1 массив сделай

### ISSUE THREAD

**Issue by antosha417** [Sergunia/prog_Bakumenko#4]
https://github.com/Sergunia/prog_Bakumenko/blob/adcd979e763bfec9cf170ee9ae297d7bcf561da6/minimalism_1.py#L23-L26
Почему сразу не сделать массив pictures. Ты же ни как не используешь picture1 и тд. Напиши просто побольше скобок.

**Comment by Sergunia** [comment]
Я же там создаю цикл:
    for step in range (len(pic)):
        draw_picture(x, y, pic[step])
        x += 200
Удобнее вроде через несколько pictures

**Comment by antosha417** [comment]
Зачем ты резервируешь имя ``Picture1`` и тд если их не используешь, а просто подряд кладешь в массив? Почему сразу такой массив не объявить?

**Comment by Sergunia** [comment]
Я сделал один массив без элементов pictures1 и тд.

Т.е. он воспринимает ( ((), (), ()), ((), (), ()) ) - как массив из 2 элементов, каждый из которых содержит какие-то кортежи.

**Comment by antosha417** [comment]
Добавь хеш коммита к своему комментарию, я просил в телеграмме об этом, спасибо.

**Comment by antosha417** [comment]
Мне кажется ты не ввёл команду git push

**Comment by Sergunia** [comment]
Мне просто строчки длинные отправить из гит лога?

**Comment by Sergunia** [comment]
commit cd68eea5a8fe6448fc65a8f6c1da8c63b2af1e06 (HEAD -> master, origin/master, origin/HEAD)
Author: Sergunia <av93210@gmail.com>
Date:   Thu Nov 1 21:19:21 2018 +0300

    changed 'Pictures' into 'pictures'

commit 3a0af9a7df06411e5424574187c6821ad65e019b
Author: Sergunia <av93210@gmail.com>
Date:   Thu Nov 1 21:13:55 2018 +0300

    spacebars, functions_names, grammar, 1 big massive

commit adcd979e763bfec9cf170ee9ae297d7bcf561da6
Author: Sergunia <av93210@gmail.com>
Date:   Fri Oct 12 14:23:47 2018 +0300

    added spacebars

commit dd848992b80579638994608169aa10fdf84730ce
Author: Sergunia <av93210@gmail.com>
Date:   Fri Oct 12 14:03:42 2018 +0300

    unlike previous code - nice code with def's

commit a18e3b761278300b2f8278636fe2f81f8ba6d0d6

**Comment by antosha417** [comment]
мне не нужен весь гит лог. Ты поправил то, что в issue и сделал коммит. Я хочу хеш этого коммита, чтобы не тратить кучу времени и не смотреть все твои коммиты.

Если что-то не понимаешь пиши в лс, будет быстрее.

**Comment by antosha417** [comment]
Также подумай как правильно коммитить, например, из сообщения коммита 3a0af9a7df06411e5424574187c6821ad65e019b  я понимаю что ты сделал много всего и решил это объединить в один коммит. Так не надо. Сделал дело, закоммитил и спокойно делай следующее.
